version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=netflix
      - MYSQL_ALLOW_EMPTY_PASSWORD=“yes”
    ports:
      - 127.0.0.1:33068:3306
    volumes:
      - ./db/mysql:/var/lib/mysql
volumes:
  db:
    driver: local